//
//  DATextDefine.h
//  Distributors
//
//  Created by Tao Yunfei on 7/31/15.
//  Copyright (c) 2015 AboveGEM. All rights reserved.
//

#import "AGTextCoordinator.h"

#define KEY_LBL_CHAT @"Chat"
#define KEY_LBL_OPPORTUNITY @"Opportunity"
#define KEY_LBL_OPPORTUNITY_TEMPLATE @"Opportunity Template"
#define KEY_LBL_OPPORTUNITIES @"Opportunities"
#define KEY_LBL_LEADERS @"Leaders"
#define KEY_LBL_LAB @"Lab"
#define KEY_LBL_CONTACT @"Contact"
#define KEY_LBL_CONTACTS @"Contacts"
#define KEY_LBL_DISCOVER @"Discover"
#define KEY_LBL_SETTING @"Setting"
#define KEY_LBL_COMPANIES @"Companies"
#define KEY_LBL_COMPANY @"Company"
#define KEY_LBL_CREATE_TEMPLATE @"Create Template"
#define KEY_LBL_TEMPLATE @"Template"
#define KEY_LBL_EARNING_POTENTIAL @"Earning Potential"
#define KEY_LBL_LIMITED_TIME_OFFER @"Limited Time Offer"
#define KEY_LBL_COMMITMENT_PERIOD @"Commitment Period"
#define KEY_LBL_MONTH @"Month"
#define KEY_LBL_WEEK @"Week"
#define KEY_LBL_DAYS @"Days"
#define KEY_LBL_MONTHS @"Months"
#define KEY_LBL_SUBJECT @"Subject"
#define KEY_LBL_DESCRIPTION @"Description"
#define KEY_LBL_TIME_TO_COMPLETE @"Time To Complete"
#define KEY_LBL_STEP @"Step"
//#define KEY_LBL_STEP_EDITOR @"Step Editor"
#define KEY_LBL_GOALS @"Goals"
#define KEY_LBL_STEPS @"Steps"
#define KEY_LBL_STEP_NAME @"Step Name"
#define KEY_LBL_NOTIFY_WHEN_COMPLETE @"Notify When Complete"
#define KEY_LBL_TASKS @"Tasks"
#define KEY_LBL_TASK_EDITOR @"Task Editor"
#define KEY_LBL_TASK_NAME @"Task Name"
#define KEY_LBL_LOCATION @"Location"
#define KEY_LBL_TIME @"Time"
#define KEY_LBL_NOTES @"Notes"
#define KEY_LBL_VIDEO_PICTURE @"Video Picture"
#define KEY_LBL_LINK @"Link"
#define KEY_LBL_LINKS @"Links"
#define KEY_LBL_REPEAT @"Repeat"
#define KEY_LBL_END @"End"
#define KEY_LBL_REMINDER @"Reminder"
#define KEY_LBL_TIME_REQUIRED @"Time Required"
#define KEY_LBL_TRAINING @"Training"
#define KEY_LBL_OTHERS @"Others"
#define KEY_LBL_AUTOSHIP @"Autoship"
#define KEY_LBL_PRODUCTS @"Products"
#define KEY_LBL_EVENTS @"Events"
#define KEY_LBL_ATTEND_EVENTS @"Attend Events"
#define KEY_LBL_HOST_EVENTS @"Host Events"
#define KEY_LBL_BIO @"Bio"
#define KEY_LBL_VIDEOS @"Videos"
#define KEY_LBL_COMMUNITY @"Community"
#define KEY_LBL_TASK_LOG @"Task Log"
#define KEY_LBL_DASHBOARD @"Dashboard"
#define KEY_LBL_REPORT @"Report"
#define KEY_LBL_LEADER_DASHBOARD @"Leader Dashboard"
#define KEY_LBL_TASK_REPORT @"Task Report"
#define KEY_LBL_TESTIMONIAL @"Testimonial"
#define KEY_LBL_PIC_AND_VCR @"Pic & Vcr"
#define KEY_LBL_NAME @"Name"
#define KEY_LBL_ADD_GOAL @"Add Goal"

#define KEY_BTN_SELECT @"Select"
#define KEY_BTN_SAVE @"Save"
#define KEY_BTN_NEXT @"Next"
#define KEY_BTN_CANCEL @"Cancel"
#define KEY_BTN_START @"Start"


#define KEY_MSG_UNDEFINED @"Undefined"
#define KEY_MSG_ADD_YOUR_FIRST_STEP @"Add Your First Step"